# Création d'un model de réseau de neurone
Dans ce tuto, nous allons réaliser un model de réseau de neurone en **Deep Learning** qui va si un patient à du cancer ou pas,
pour cela notre model sera entrainer sur la dataset **Breast cancer** de **wisconsin** 

## Importation des package

In [18]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
import pandas as pd

## Création de la dataset

In [19]:
df = datasets.load_breast_cancer()
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [20]:
X=df.data
y=df.target
print(f'X={X.shape} et y={y.shape}')

X=(569, 30) et y=(569,)


## Data préprocessing(Ou pré traitement des données)

In [84]:
## Le variable indépendantes
df.data[:2]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02]])

In [74]:
missing_values=0
for i,v in enumerate(X.isna()):
    for ii in X.isna()[i]:
        if ii == True:
            missing_values += 1            
print(f'Il y a {missing_values} valeur(s) manquante(s)')

Il y a 0 valeur(s) manquante(s)


In [88]:
## les target value ou variables dependnce ou à predire
y = df.target
y[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

## Standardisation des valeurs

In [85]:
scaler = StandardScaler()

In [98]:
X_scled = scaler.fit_transform(X, y)

## Création de train et test set

In [101]:
x_train, x_test, y_train, y_test = train_test_split(X_scled, y, test_size=0.25, random_state=42 )

In [104]:
print(f'La tailles de train set: {x_train.shape[0]} \nLa tailles de test set: {x_test.shape[0]}')

La tailles de train set: 426 
La tailles de test set: 143


## Création de modèle de réseau de neurone

In [148]:
model = tf.keras.models.Sequential()

In [149]:
couche_entree = tf.keras.layers.Dense(units=15, activation='relu', kernel_initializer="uniform", input_dim=30)
# couche_cachee = tf.keras.layers.Dense(units=15, activation='relu', kernel_initializer="uniform")
couche_sortie = tf.keras.layers.Dense(units=1, activation='sigmoid', kernel_initializer="uniform")

In [150]:
model.add(couche_entree)
# model.add(couche_cachee)
model.add(couche_sortie)

In [151]:
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['binary_accuracy'])

In [152]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 15)                465       
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 16        
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________


In [153]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
14/14 [==============================] - 0s 3ms/step - loss: 0.6838 - binary_accuracy: 0.8357
Epoch 2/100
14/14 [==============================] - 0s 1ms/step - loss: 0.6544 - binary_accuracy: 0.9319
Epoch 3/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6089 - binary_accuracy: 0.9272
Epoch 4/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5503 - binary_accuracy: 0.9249
Epoch 5/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4857 - binary_accuracy: 0.9319
Epoch 6/100
14/14 [==============================] - 0s 1ms/step - loss: 0.4257 - binary_accuracy: 0.9390
Epoch 7/100
14/14 [==============================] - 0s 2ms/step - loss: 0.3731 - binary_accuracy: 0.9484
Epoch 8/100
14/14 [==============================] - 0s 2ms/step - loss: 0.3276 - binary_accuracy: 0.9554
Epoch 9/100
14/14 [==============================] - 0s 2ms/step - loss: 0.2900 - binary_accuracy: 0.9601
Epoch 10/100
14/14 [==========================

14/14 [==============================] - 0s 2ms/step - loss: 0.0498 - binary_accuracy: 0.9836
Epoch 78/100
14/14 [==============================] - 0s 1ms/step - loss: 0.0495 - binary_accuracy: 0.9836
Epoch 79/100
14/14 [==============================] - 0s 1ms/step - loss: 0.0491 - binary_accuracy: 0.9836
Epoch 80/100
14/14 [==============================] - 0s 1ms/step - loss: 0.0490 - binary_accuracy: 0.9836
Epoch 81/100
14/14 [==============================] - 0s 2ms/step - loss: 0.0485 - binary_accuracy: 0.9836
Epoch 82/100
14/14 [==============================] - 0s 2ms/step - loss: 0.0481 - binary_accuracy: 0.9836
Epoch 83/100
14/14 [==============================] - 0s 2ms/step - loss: 0.0477 - binary_accuracy: 0.9836
Epoch 84/100
14/14 [==============================] - 0s 1ms/step - loss: 0.0474 - binary_accuracy: 0.9836
Epoch 85/100
14/14 [==============================] - 0s 2ms/step - loss: 0.0471 - binary_accuracy: 0.9836
Epoch 86/100
14/14 [==============================

In [154]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)

5/5 [==============================] - 0s 1ms/step - loss: 0.0551 - binary_accuracy: 0.9790


In [155]:
print(f'Test Loss: {test_loss}\nTest Accuracy: {test_accuracy}')

Test Loss: 0.055100373923778534
Test Accuracy: 0.9790209531784058


In [178]:
model.predict(np.array([x_test[8]]))

array([[0.61471105]], dtype=float32)

In [179]:

y_test[8]

1